name: 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: git clone
      run: |
        git clone -b frankrust https://github.com/Java-S12138/frank

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Build Frank
      run: |
        cd frank/src
        pnpm install
        cd ../src-tauri
        pnpm run tauri build

    - name: Set variables
      run: |
        $date = Get-Date -Format "yyyyMMddHHmm"
        echo "TAG_DATE=$date" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
