name: Build 1

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_caddy_with_NT:
    runs-on: ubuntu-latest
    env:
      BUNDLE: caddy-forwardproxy-naive
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.25
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: |
          CGO_ENABLED=0 ~/go/bin/xcaddy build --output caddy

      - name: Set variables
        run: |
          echo "TAG_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name:  Upload caddy (Linux & Windows)
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: caddy-${{ env.TAG_DATE }}
          name: caddy-${{ env.TAG_DATE }}
          files: |
            caddy
            caddy.exe
          preserve_order: true
          draft: false
          prerelease: true
          make_latest: false
